<script lang="ts">
  import { onMount } from 'svelte';
  import { api, ApiError, setAccessToken } from './api';
  import type { Probe, ProbeInput, Summary } from './types';
  import { checkoutUrl, consumeLicenseFromUrl, storeToken, storedToken, verifyLicense, type LicenseState } from './license';

  const empty:Summary={probes:[],alerts:[],observations:[]};
  const fresh=():ProbeInput=>({name:'',provider:'',endpoint_url:'https://api.openai.com/v1/chat/completions',model:'',api_key:'',prompt:'Return JSON with exactly {"status":"ok","region":"canary"}.',required_fields:['status','region'],interval_minutes:5,timeout_ms:15000,latency_slo_ms:3000,availability_slo_percent:99,max_output_tokens:128,daily_token_cap:5000,enabled:true});
  let data:Summary=empty,loading=true,loadError='',offline=!navigator.onLine,busy='',toast='',formError='',fieldsText='status, region',accessCode='',accessNeeded=false;
  let form:ProbeInput=fresh(),editing:Probe|null=null,expanded='',confirming='';
  let probeDialog:HTMLDialogElement,planDialog:HTMLDialogElement,firstField:HTMLInputElement;
  let license:LicenseState={unlocked:false,checking:false,notice:'',token:''},licenseInput='';
  const path=location.pathname;
  $: openAlerts=data.alerts.filter(a=>a.status==='open');
  $: healthy=data.probes.filter(p=>p.last_observation?.outcome==='healthy').length;
  $: availability=data.probes.length?data.probes.reduce((n,p)=>n+p.stats.availability_percent,0)/data.probes.length:0;
  $: avgLatency=data.probes.length?Math.round(data.probes.reduce((n,p)=>n+p.stats.p95_latency_ms,0)/data.probes.length):0;

  onMount(()=>{
    const incoming=consumeLicenseFromUrl();const token=incoming||storedToken();if(token){license={...license,checking:true,token};verifyLicense(token).then(v=>license=v)}
    const saved=sessionStorage.getItem('capacity-sentinel-access');if(saved){accessCode=saved;setAccessToken(saved)}
    if(path==='/'||path==='/index.html'){
      if(saved)load();
      else{loading=false;accessNeeded=true}
    }
    const online=()=>{offline=false;if(accessCode)load()},off=()=>offline=true;window.addEventListener('online',online);window.addEventListener('offline',off);
    const timer=setInterval(()=>{if(accessCode&&!offline&&!document.hidden)load(false)},30000);
    return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',off);clearInterval(timer)};
  });
  async function load(show=true){if(show)loading=true;try{data=await api.summary();loadError='';accessNeeded=false}catch(e){accessNeeded=e instanceof ApiError&&e.status===401;loadError=accessNeeded?'':e instanceof Error?e.message:'Could not load observations'}finally{loading=false}}
  async function unlock(){if(!accessCode.trim())return;setAccessToken(accessCode.trim());sessionStorage.setItem('capacity-sentinel-access',accessCode.trim());await load()}
  function openCreate(){editing=null;form=fresh();fieldsText='status, region';formError='';probeDialog.showModal();setTimeout(()=>firstField?.focus())}
  function openEdit(p:Probe){editing=p;form={name:p.name,provider:p.provider,endpoint_url:p.endpoint_url,model:p.model,api_key:'',prompt:'',required_fields:p.required_fields,interval_minutes:p.interval_minutes,timeout_ms:p.timeout_ms,latency_slo_ms:p.latency_slo_ms,availability_slo_percent:p.availability_slo_percent,max_output_tokens:p.max_output_tokens,daily_token_cap:p.daily_token_cap,enabled:p.enabled};fieldsText=p.required_fields.join(', ');formError='';probeDialog.showModal();setTimeout(()=>firstField?.focus())}
  async function save(){busy='save';formError='';form.required_fields=fieldsText.split(',').map(v=>v.trim()).filter(Boolean);try{editing?await api.update(editing.id,form):await api.create(form);probeDialog.close();toast=editing?'Specimen updated':'Canary planted. Its first observation is due now.';await load(false)}catch(e){formError=e instanceof Error?e.message:'Could not save probe'}finally{busy='';setTimeout(()=>toast='',5000)}}
  async function run(p:Probe){busy=p.id;try{await api.run(p.id);toast=`Observation complete for ${p.name}`;await load(false)}catch(e){toast=e instanceof Error?e.message:'Observation failed'}finally{busy='';setTimeout(()=>toast='',5000)}}
  async function exportCsv(){try{const blob=await api.exportCsv(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='capacity-sentinel-observations.csv';link.click();URL.revokeObjectURL(url)}catch(e){toast=e instanceof Error?e.message:'Could not export observations'}}
  async function remove(p:Probe){if(confirming!==p.id){confirming=p.id;setTimeout(()=>confirming='',5000);return}busy=p.id;try{await api.remove(p.id);toast=`Removed ${p.name} and its local history`;confirming='';await load(false)}catch(e){toast=e instanceof Error?e.message:'Could not remove probe'}finally{busy=''}}
  async function restore(){if(!licenseInput.trim())return;storeToken(licenseInput);license={unlocked:false,checking:true,notice:'Checking license…',token:licenseInput.trim()};license=await verifyLicense(licenseInput.trim(),true);licenseInput=''}
  function fmt(date:string){return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(date))}
  function status(p:Probe){if(!p.enabled)return'paused';if(!p.last_observation)return'awaiting';return p.last_observation.outcome}
  function probeName(id:string){return data.probes.find(p=>p.id===id)?.name||'Removed probe'}
  function atlasStats(p:Probe){const rows=data.observations.filter(o=>o.probe_id===p.id);const ok=rows.filter(o=>o.outcome==='healthy').length;const latency=rows.filter(o=>o.http_status!==null).map(o=>o.latency_ms).sort((a,b)=>a-b);return{count:rows.length,availability:rows.length?ok/rows.length*100:0,p95:latency[Math.max(0,Math.ceil(latency.length*.95)-1)]||0}}
</script>

<a class="skip" href="#main">Skip to main content</a>
<header class="site-head">
  <a class="brand" href="/" aria-label="Capacity Sentinel home"><span class="brand-mark" aria-hidden="true">⌁</span><span>Capacity<br><b>Sentinel</b></span></a>
  <nav aria-label="Main navigation">
    <a href="/#observations">Observations</a><a href="/#field-notes">Field notes</a><button class="nav-plan" on:click={()=>planDialog?.showModal()}>Atlas plan</button>
  </nav>
  {#if path==='/'||path==='/index.html'}<div class="live-mark"><span class:warning={openAlerts.length>0}></span>{openAlerts.length?`${openAlerts.length} active alert${openAlerts.length===1?'':'s'}`:'System quiet'}</div>{/if}
</header>

{#if path==='/privacy'}
  <main id="main" class="legal"><p class="eyebrow">Field note 01 · Updated 28 August 2026</p><h1>Privacy, by habitat.</h1><p class="lede">Capacity Sentinel is designed to run where your infrastructure lives. We do not operate an analytics pipeline and we do not receive your model credentials, canary prompts, or observations.</p><h2>What the local runner stores</h2><p>The self-hosted service stores probe configuration, encrypted synthetic canaries and API keys, model identifiers, observation timings, status codes, token counts, validation results, and alerts in its local SQLite database. Canary text is never returned by the API or displayed after saving. Secrets use AES-256-GCM with a locally persisted 0600 key or your <code>SENTINEL_MASTER_KEY</code>.</p><h2>What leaves your system</h2><p>Your encrypted-in-storage synthetic canary and API credential are decrypted only to make the request to the public endpoint you configure. If you buy or verify an Atlas license, the token is sent to Sociobot’s billing API. The token is stored in your browser; checkout is handled by Sociobot/Dodo as merchant of record.</p><h2>Your control</h2><p>Delete a specimen to remove its configuration, observations, and alerts. Delete the mounted data directory to remove the whole installation. CSV export is always available and never paywalled.</p><h2>Contact</h2><p>Questions can be sent to <a href="mailto:privacy@sociobot.in">privacy@sociobot.in</a>.</p></main>
{:else if path==='/terms'}
  <main id="main" class="legal"><p class="eyebrow">Field note 02 · Updated 27 August 2026</p><h1>Terms of use.</h1><p class="lede">Capacity Sentinel is a synthetic availability and output-shape monitor. It is evidence for operators, not a guarantee of provider availability or model quality.</p><h2>Appropriate use</h2><p>Use synthetic prompts you are authorized to send. Do not place production customer content or personal data in canaries. You are responsible for provider terms, endpoint access, token charges, and reasonable probe intervals.</p><h2>No semantic-quality claim</h2><p>The service checks transport status, elapsed request latency, parseable JSON, and fields you specify. It does not measure truthfulness, universal model quality, or fitness for a particular decision.</p><h2>Atlas license</h2><p>The $39 Atlas unlock is a one-time purchase for the extended comparison view in this product release. Sociobot/Dodo is merchant of record. Refunds are handled there and revoke the associated license. Accessibility, safety notices, and CSV export remain available without a license.</p><h2>Warranty and liability</h2><p>The software is provided “as is” under the MIT License. Verify alerts against provider evidence before making high-impact operational decisions.</p></main>
{:else}
<main id="main">
  {#if offline}<div class="offline" role="status"><b>Offline field mode.</b> Showing the last observations on this screen. Reconnect to run or edit canaries.</div>{/if}
  {#if toast}<div class="toast" role="status">{toast}</div>{/if}
  <section class="hero" aria-labelledby="page-title">
    <div class="hero-copy"><p class="eyebrow">Vendor-neutral model API canaries · v1.0</p><h1 id="page-title">Notice the change<br><i>before users do.</i></h1><p class="lede">Send small synthetic probes. Catch capacity errors, latency regressions, and broken JSON contracts across model providers—without retaining production prompts.</p><div class="hero-actions"><button class="primary" on:click={openCreate}>Plant a canary <span aria-hidden="true">↗</span></button><a class="text-link" href="#field-notes">Read the field method <span aria-hidden="true">↓</span></a></div><div class="trust-row"><span><b>Local first</b><small>SQLite on your host</small></span><span><b>Keys encrypted</b><small>AES-256-GCM</small></span><span><b>Shape aware</b><small>Your JSON invariants</small></span></div></div>
    <figure class="hero-art"><img src="/assets/hero-field-guide.webp" width="1200" height="800" fetchpriority="high" decoding="async" alt="Engraved botanical network with model endpoints preserved in glass pods and one drooping ochre leaf indicating degradation"><figcaption><span>Plate CS–01</span> A model habitat under observation</figcaption></figure>
  </section>

  <section class="dashboard" id="observations" aria-labelledby="overview-title">
    <div class="section-heading"><div><p class="eyebrow">Live field sheet</p><h2 id="overview-title">Current observations</h2></div><div class="actions"><button class="secondary" on:click={exportCsv}>Export CSV</button><button class="primary" on:click={openCreate}>Add probe</button></div></div>
    {#if loading}<div class="loading" role="status"><span></span>Preparing the field sheet…</div>
    {:else if accessNeeded}<div class="state error-state"><span aria-hidden="true">⌁</span><div><h3>Open this project’s field sheet</h3><p>Enter the project access code supplied by the runner owner. It is kept only for this browser session.</p><label>Project access code<input type="password" bind:value={accessCode} autocomplete="off" on:keydown={(e)=>e.key==='Enter'&&unlock()}></label><button class="secondary" on:click={unlock}>Open field sheet</button></div></div>
    {:else if loadError}<div class="state error-state" role="alert"><span aria-hidden="true">×</span><div><h3>The field sheet could not be read</h3><p>{loadError}. Check that the local runner is online, then try again.</p><button class="secondary" on:click={()=>load()}>Try again</button></div></div>
    {:else if !data.probes.length}<div class="state empty-state"><span class="empty-glyph" aria-hidden="true">⌇</span><div><h3>No specimens yet</h3><p>Add a synthetic, non-sensitive prompt and the JSON fields it must return. The runner will establish a baseline automatically.</p><button class="primary" on:click={openCreate}>Add your first probe</button></div></div>
    {:else}
      <div class="metrics" aria-label="Fleet summary"><article><span>01 / Availability</span><strong>{availability.toFixed(1)}%</strong><small>Rolling 20 observations per probe</small></article><article><span>02 / Healthy specimens</span><strong>{healthy}<em> / {data.probes.length}</em></strong><small>{openAlerts.length?`${openAlerts.length} alert${openAlerts.length===1?'':'s'} need attention`:'No open alerts'}</small></article><article><span>03 / Mean p95 latency</span><strong>{avgLatency}<em> ms</em></strong><small>Non-streaming elapsed request time</small></article></div>
      {#if openAlerts.length}<div class="alerts" aria-labelledby="alerts-title"><div class="margin-label">ACTIVE<br>PRESSINGS</div><div><h3 id="alerts-title">Changes worth inspecting</h3>{#each openAlerts as alert}<article><span class="alert-pin" aria-hidden="true">!</span><div><b>{probeName(alert.probe_id)} · {alert.kind.replace('_',' ')}</b><p>{alert.message}</p><small>Opened {fmt(alert.opened_at)}</small></div></article>{/each}</div></div>{/if}
      <div class="specimens"><div class="table-head"><span>Specimen / endpoint</span><span>Last outcome</span><span>Rolling evidence</span><span><span class="sr-only">Actions</span></span></div>
      {#each data.probes as p, i}
        <article class="specimen" class:open={expanded===p.id}>
          <div class="specimen-row"><button class="expand" aria-expanded={expanded===p.id} aria-controls={'details-'+p.id} on:click={()=>expanded=expanded===p.id?'':p.id}><span class="number">{String(i+1).padStart(2,'0')}</span><span><b>{p.name}</b><small>{p.provider} · {p.model}</small></span><span class="chevron" aria-hidden="true">⌄</span></button><div><span class={'status '+status(p)}><i></i>{status(p)}</span><small>{p.last_observation?fmt(p.last_observation.started_at):'First run pending'}</small></div><div class="evidence"><b>{p.stats.availability_percent.toFixed(1)}% <small>available</small></b><b>{p.stats.p95_latency_ms} ms <small>p95</small></b><div class="ticks" role="img" aria-label={`${p.stats.consecutive_failures} consecutive failures`}>{#each Array(Math.min(10,Math.max(1,p.stats.sample_count))) as _, j}<i class:bad={j<p.stats.consecutive_failures}></i>{/each}</div></div><div class="row-actions"><button class="icon-button" title={'Observe '+p.name} aria-label={'Observe '+p.name+' now'} disabled={busy===p.id||offline} on:click={()=>run(p)}>{busy===p.id?'…':'↻'}</button><button class="icon-button" title={'Edit '+p.name} aria-label={'Edit '+p.name}>✎</button></div></div>
          {#if expanded===p.id}<div class="details" id={'details-'+p.id}><div><p class="label">Synthetic canary</p><p>Stored encrypted and never displayed after saving.</p><p class="label">Required fields</p><p>{p.required_fields.length?p.required_fields.join(' · '):'Valid JSON only'}</p></div><div><p class="label">Guardrails</p><dl><div><dt>Interval</dt><dd>{p.interval_minutes} min</dd></div><div><dt>Timeout</dt><dd>{p.timeout_ms} ms</dd></div><div><dt>Daily budget</dt><dd>{p.stats.tokens_today} / {p.daily_token_cap} tokens</dd></div><div><dt>Endpoint</dt><dd class="truncate" title={p.endpoint_url}>{p.endpoint_url}</dd></div></dl></div><div class="detail-actions"><button class="secondary" on:click={()=>run(p)} disabled={busy===p.id||offline}>Observe now</button><button class="quiet-danger" on:click={()=>remove(p)}>{confirming===p.id?'Confirm remove':'Remove specimen'}</button>{#if confirming===p.id}<small>This also deletes its local history.</small>{/if}</div></div>{/if}
        </article>
      {/each}</div>
    {/if}
  </section>

  {#if license.unlocked && data.probes.length}<section class="atlas-notebook" aria-labelledby="notebook-title"><div class="section-heading"><div><p class="eyebrow">Atlas · 365-day notebook</p><h2 id="notebook-title">Cross-provider comparison</h2></div><span class="license-ok">✓ Licensed</span></div><div class="atlas-table"><div class="atlas-row atlas-head"><span>Provider / model</span><span>Observations</span><span>Availability</span><span>p95 latency</span></div>{#each data.probes as p}<div class="atlas-row"><b>{p.provider}<small>{p.model}</small></b><span>{atlasStats(p).count}</span><span>{atlasStats(p).availability.toFixed(1)}%</span><span>{atlasStats(p).p95} ms</span></div>{/each}</div></section>{/if}

  <section class="method" id="field-notes" aria-labelledby="method-title"><div class="method-intro"><p class="eyebrow">The field method</p><h2 id="method-title">Comparable evidence,<br>not another tracing proxy.</h2><p>Capacity Sentinel never sits in your production path. It asks each provider the same small, scheduled question and records only operational evidence.</p></div><ol><li><span>01</span><div><h3>Plant a synthetic canary</h3><p>Use a harmless prompt made for monitoring. Credentials stay encrypted on your host.</p></div></li><li><span>02</span><div><h3>Declare the invariant</h3><p>Name the JSON paths that must exist. We test shape, not subjective truth or universal “quality.”</p></div></li><li><span>03</span><div><h3>Watch the habitat change</h3><p>Two consecutive failures raise an attributed alert. Rolling p95 latency reveals slower drift.</p></div></li></ol></section>

  <section class="atlas" aria-labelledby="atlas-title"><div><p class="eyebrow">Optional Atlas license</p><h2 id="atlas-title">Keep the local runner free.<br>Open a longer field view.</h2><p>The free tier runs every core canary, stores local evidence, raises alerts, and exports CSV. Atlas adds the extended 365-day comparison view and supports managed probe locations as they become available.</p></div><div class="price"><span>One-time</span><strong>$39</strong><small>No subscription. Sociobot/Dodo is merchant of record.</small>{#if license.unlocked}<p class="license-ok">✓ {license.notice}</p>{:else}<a class="button primary" href={checkoutUrl}>Unlock Atlas</a><button class="text-link" on:click={()=>planDialog.showModal()}>Have a license? Restore it</button>{/if}</div></section>
</main>
{/if}

<footer><div class="brand mini"><span class="brand-mark" aria-hidden="true">⌁</span><span>Capacity <b>Sentinel</b></span></div><p>Synthetic evidence for model API operators. Generated botanical artwork; original to this product.</p><nav aria-label="Legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="https://github.com/B-Divyesh/sf-model-capacity-sentinel">Source</a></nav></footer>

<dialog class="probe-dialog" bind:this={probeDialog} on:close={()=>{formError='';confirming=''}}>
  <form method="dialog" on:submit={(e)=>{e.preventDefault();save()}}><header><div><p class="eyebrow">{editing?'Revise specimen':'New specimen'}</p><h2>{editing?'Edit canary':'Plant a canary'}</h2></div><button type="button" class="close" aria-label="Close dialog" on:click={()=>probeDialog.close()}>×</button></header><p class="dialog-intro">Use a synthetic prompt only—never customer content. This runner currently supports OpenAI-compatible chat completion endpoints.</p>
    <div class="form-grid"><label>Canary name<input bind:this={firstField} bind:value={form.name} required maxlength="80" placeholder="EU capacity check"></label><label>Provider label<input bind:value={form.provider} required maxlength="50" placeholder="Provider or region"></label><label class="wide">Chat completion endpoint<input type="url" bind:value={form.endpoint_url} required aria-describedby="endpoint-help"><small id="endpoint-help">Public HTTP(S) endpoint only; private, loopback, and link-local addresses are blocked.</small></label><label>Model<input bind:value={form.model} required placeholder="model-name"></label><label>API key<input type="password" bind:value={form.api_key} required={!editing} autocomplete="off" placeholder={editing?'Leave blank to keep stored key':'sk-…'}><small>Encrypted before SQLite storage.</small></label><label class="wide">Synthetic prompt<textarea bind:value={form.prompt} required={!editing} rows="3" placeholder={editing?'Leave blank to keep the encrypted canary':'A harmless monitoring question'}></textarea><small>Encrypted before storage and never shown again.</small></label><label class="wide">Required JSON paths<input bind:value={fieldsText} placeholder="status, result.label"><small>Comma-separated dot paths. Leave empty to require valid JSON only.</small></label>
      <fieldset class="wide"><legend>Schedule and objectives</legend><label>Every (minutes)<input type="number" min="1" max="1440" bind:value={form.interval_minutes}></label><label>Timeout (ms)<input type="number" min="1000" max="120000" step="500" bind:value={form.timeout_ms}></label><label>p95 target (ms)<input type="number" min="100" max="120000" step="100" bind:value={form.latency_slo_ms}></label><label>Availability target (%)<input type="number" min="1" max="100" step="0.1" bind:value={form.availability_slo_percent}></label><label>Max output tokens<input type="number" min="1" max="8192" bind:value={form.max_output_tokens}></label><label>Daily token cap<input type="number" min="1" max="10000000" bind:value={form.daily_token_cap}></label></fieldset><label class="check wide"><input type="checkbox" bind:checked={form.enabled}><span>Run this canary on schedule</span></label>
    </div>{#if formError}<p class="form-error" role="alert">{formError}</p>{/if}<footer><button type="button" class="secondary" on:click={()=>probeDialog.close()}>Cancel</button><button class="primary" type="submit" disabled={busy==='save'}>{busy==='save'?'Saving…':editing?'Save changes':'Plant canary'}</button></footer>
  </form>
</dialog>

<dialog class="plan-dialog" bind:this={planDialog}><form method="dialog"><header><div><p class="eyebrow">Atlas license</p><h2>A longer field of view</h2></div><button class="close" value="cancel" aria-label="Close dialog">×</button></header><p>Atlas is a <b>$39 one-time purchase</b>. It unlocks the extended comparison view; checkout and refunds are handled by Sociobot/Dodo.</p>{#if license.unlocked}<p class="license-ok">✓ Atlas license active on this browser.</p>{:else}<a class="button primary full" href={checkoutUrl}>Buy Atlas — $39 once</a><div class="restore"><label for="license">Have a license? Paste it here</label><input id="license" bind:value={licenseInput} autocomplete="off" placeholder="License token"><button type="button" class="secondary" on:click={restore} disabled={license.checking}>{license.checking?'Verifying…':'Verify license'}</button></div>{#if license.notice}<p class="license-notice" role="status">{license.notice}</p>{/if}{/if}<small>By purchasing, you agree to the <a href="/terms">terms</a>. See our <a href="/privacy">privacy notice</a>.</small></form></dialog>
